# ===============================
# ========== DATABASE ==========
# ===============================
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=phoneShop;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # ===============================
  # ========== JPA ===============
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  
  cache:
    type: simple 

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html